dist: trusty
language: node_js
node_js:
  - '8.9.4'

branches:
  only:
  - master
  - develop
  - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules

env:
  global:

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

